## Numpy Practice Session

In [2]:
# pip install numpy

In [3]:
# import this library in j.notebook
import numpy as np

## Creating an Array using Numpy

In [5]:
# 1-D array
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [6]:
price = np.array([5, 5, 5]) 
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [9]:
len(price)

3

In [10]:
len(food)

3

In [14]:
price[0:] 

array([5, 5, 5])

In [17]:
food[1]

'Samosa'

In [18]:
price.mean()

5.0

In [21]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [24]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# spacify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [28]:
# specific intervel
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [38]:
# line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [7]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array Function

In [8]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [9]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [10]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [12]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [14]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

## 2-D Arrays

In [19]:
a = np.array([[1,2,3,4],[5,4,3,2]])
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [20]:
b = np.array([[6,7,8,9],[10,11,12,13]])
b

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [21]:
c = np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4],
       [ 5,  4,  3,  2],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [22]:
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  6,  7,  8,  9],
       [ 5,  4,  3,  2, 10, 11, 12, 13]])

In [24]:
a = np.array([[[0,1,2,3],
               [4,5,6,7]],
                         
              [[0,1,2,3],
               [4,5,6,7]],
                         
              [[0,1,2,3],
               [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [25]:
# to find the number of dimentions
a.ndim

3

In [28]:
type(a)

numpy.ndarray

In [26]:
b = np.array([[5,6,7],
             [8,9,10],
             [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [27]:
b.ndim

2

In [29]:
# size (number of elements)
a.size

24

In [32]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [31]:
# shape
a.shape

(3, 2, 4)

In [36]:
a = np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
# reshape
a = a.reshape(3,3) #3*3=9
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
# reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [40]:
# convert 1-D into 2-D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.shape

(9,)

In [42]:
# row wise 2-D
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b.shape

(1, 9)

In [44]:
# column wise 2-D
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [48]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [49]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
a.sum()

45

In [52]:
a.mean()

5.0